### ISSUE TITLE
bootstrap switch is breaking bootstrap-datepicker

### ISSUE THREAD

**Issue by alberthild** [Nerian/bootstrap-datepicker-rails#48]
See:
https://github.com/nostalgiaz/bootstrap-switch/issues/27

For those who want to solve that quick:

``` css
.datepicker .switch {
  display: table-cell;
}
```
